# Generated by Django 3.1.1 on 2021-04-16 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='kagglefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaggle_field', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psw', models.CharField(default='0000', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('test_t', models.IntegerField(default=0, null=True)),
                ('test_t1', models.IntegerField(default=0, null=True)),
                ('test_t2', models.IntegerField(default=0, null=True)),
                ('test_t3', models.IntegerField(default=0, null=True)),
                ('test_t4', models.IntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('nums', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(choices=[('py', 'Python程式設計'), ('ml', '機器學習')], max_length=2)),
                ('password', models.CharField(default='0000', max_length=20)),
                ('userid', models.CharField(max_length=9, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.team')),
            ],
            options={
                'ordering': ['userid'],
            },
        ),
        migrations.CreateModel(
            name='kagscore4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='kagscore3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='kagscore2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='kagscore1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='biweekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('num', models.IntegerField(null=True)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.week')),
            ],
            options={
                'ordering': ['week', 'num'],
            },
        ),
    ]
