# Generated by Django 3.0.3 on 2020-08-22 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psw', models.CharField(default='0000', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(choices=[('py', 'Python程式設計'), ('ml', '機器學習')], max_length=2)),
                ('password', models.CharField(default='0000', max_length=20)),
                ('userid', models.CharField(max_length=9, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.Team')),
            ],
            options={
                'ordering': ['userid'],
            },
        ),
        migrations.CreateModel(
            name='biweekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.FloatField(default=0.0, null=True)),
                ('num2', models.FloatField(default=0.0, null=True)),
                ('num3', models.FloatField(default=0.0, null=True)),
                ('num4', models.FloatField(default=0.0, null=True)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.User')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Week')),
            ],
        ),
    ]
