# Generated by Django 3.1.1 on 2021-04-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biweekly',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='biweekly',
            name='week',
        ),
        migrations.DeleteModel(
            name='chatmes',
        ),
        migrations.DeleteModel(
            name='kagglefile',
        ),
        migrations.RemoveField(
            model_name='kagscore1',
            name='team',
        ),
        migrations.RemoveField(
            model_name='kagscore2',
            name='team',
        ),
        migrations.RemoveField(
            model_name='kagscore3',
            name='team',
        ),
        migrations.RemoveField(
            model_name='kagscore4',
            name='team',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.DeleteModel(
            name='biweekly',
        ),
        migrations.DeleteModel(
            name='kagscore1',
        ),
        migrations.DeleteModel(
            name='kagscore2',
        ),
        migrations.DeleteModel(
            name='kagscore3',
        ),
        migrations.DeleteModel(
            name='kagscore4',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
