# Generated by Django 3.1.1 on 2020-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biweekly',
            options={'ordering': ['week', 'num']},
        ),
        migrations.RemoveField(
            model_name='biweekly',
            name='num1',
        ),
        migrations.RemoveField(
            model_name='biweekly',
            name='num2',
        ),
        migrations.RemoveField(
            model_name='biweekly',
            name='num3',
        ),
        migrations.RemoveField(
            model_name='biweekly',
            name='num4',
        ),
        migrations.AddField(
            model_name='biweekly',
            name='num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='biweekly',
            name='sco',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='nums',
            field=models.IntegerField(null=True),
        ),
    ]
