# Generated by Django 3.1.1 on 2021-04-16 07:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='kagglefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaggle_field', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='biweekly',
            options={'ordering': ['week', 'num']},
        ),
        migrations.RenameField(
            model_name='biweekly',
            old_name='num1',
            new_name='sco',
        ),
        migrations.RemoveField(
            model_name='biweekly',
            name='num2',
        ),
        migrations.RemoveField(
            model_name='biweekly',
            name='num3',
        ),
        migrations.RemoveField(
            model_name='biweekly',
            name='num4',
        ),
        migrations.AddField(
            model_name='biweekly',
            name='num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='test_t',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='test_t1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='test_t2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='test_t3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='test_t4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='nums',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='kagscore4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='kagscore3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='kagscore2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='kagscore1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='kagscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
