# Generated by Django 3.1.1 on 2020-09-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200902_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
