# Generated by Django 3.1.1 on 2021-04-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20210416_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kagscore',
        ),
    ]
