# Generated by Django 3.1.1 on 2021-04-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_geeksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='kagglefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaggle_field', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='kagscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('num', models.IntegerField(null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.week')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='kagscore1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('num', models.IntegerField(null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.week')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='kagscore2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('num', models.IntegerField(null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.week')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='kagscore3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('num', models.IntegerField(null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.week')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='kagscore4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sco', models.FloatField(default=0.0, null=True)),
                ('num', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
        migrations.AddField(
            model_name='team',
            name='test_t',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kagscore4',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team'),
        ),
        migrations.AddField(
            model_name='kagscore4',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.week'),
        ),
        migrations.AddField(
            model_name='kagscore3',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team'),
        ),
        migrations.AddField(
            model_name='kagscore2',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team'),
        ),
        migrations.AddField(
            model_name='kagscore1',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team'),
        ),
        migrations.AddField(
            model_name='kagscore',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.team'),
        ),
    ]
