# Generated by Django 3.1.1 on 2021-04-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20210411_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kagglefile',
            name='kaggle_field',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='test_t',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
