# Generated by Django 3.1.1 on 2021-04-11 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20210411_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kagscore',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='kagscore1',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='kagscore2',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='kagscore3',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='kagscore4',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='kagscore',
            name='num',
        ),
        migrations.RemoveField(
            model_name='kagscore1',
            name='num',
        ),
        migrations.RemoveField(
            model_name='kagscore2',
            name='num',
        ),
        migrations.RemoveField(
            model_name='kagscore3',
            name='num',
        ),
        migrations.RemoveField(
            model_name='kagscore4',
            name='num',
        ),
        migrations.RemoveField(
            model_name='kagscore4',
            name='week',
        ),
        migrations.AddField(
            model_name='kagscore4',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='test_t1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='test_t2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='test_t3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='test_t4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kagscore',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kagscore1',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kagscore2',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kagscore3',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
